/** @format */

// User reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
// export const MARK_NOTIFICATIONS_READ = "MARK_NOTIFICATIONS_READ";
// UI reducer types
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING_DATA = "LOADING_DATA";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
// Data reducer types
export const ADD_SCREAMS = "ADD_SCREAMS";
export const SET_SCREAMS = "SET_SCREAMS";
export const SET_SCREAM = "SET_SCREAM";
export const LIKE_SCREAM = "LIKE_SCREAM";
export const UNLIKE_SCREAM = "UNLIKE_SCREAM";
export const DELETE_SCREAM = "DELETE_SCREAM";
export const POST_SCREAM = "POST_SCREAM";

export const EDIT_SCREAM = "EDIT_SCREAM";

export const SUBMIT_COMMENT = "SUBMIT_COMMENT";

export const SET_COMMENTS = "SET_COMMENTS";
export const SET_COMMENT = "SET_COMMENT";

export const DELETE_COMMENT = "DELETE_COMMENT";

export const LOADING_PROJECTS_DATA = "LOADING_PROJECTS_DATA";

export const SET_PROJECTS = "SET_PROJECTS";
export const SET_PROJECT_SCREAMS = "SET_PROJECT_SCREAMS";
export const LOADING_PROJECT_SCREAMS = "LOADING_PROJECT_SCREAMS";

export const LOADING_MY_SCREAMS = "LOADING_MY_SCREAMS";
export const SET_MY_SCREAMS = "SET_MY_SCREAMS";

export const SUBMIT_CHAT = "SUBMIT_CHAT";

export const OPEN_SCREAM = "OPEN_SCREAM";
export const CLOSE_SCREAM = "CLOSE_SCREAM";

export const OPEN_PROJECT = "OPEN_PROJECT";
export const CLOSE_PROJECT = "CLOSE_PROJECT";

export const CLEAR_LOADING_ERRORS = "CLEAR_LOADING_ERRORS";

export const SET_SCREAM_USER = "SET_SCREAM_USER";

export const SET_FULL_SCREAMS = "SET_FULL_SCREAMS";

export const OPEN_MONITORING_SCREAM = "OPEN_MONITORING_SCREAM";
export const CLOSE_MONITORING_SCREAM = "CLOSE_MONITORING_SCREAM";

export const SET_COOKIES = "SET_COOKIES";
